import type { TFunction } from "i18next";
import type { SpaceDetailCopy } from "../space-detail/copy";
import type { SpacesOverviewLabels } from "../spaces";

export function createSpacesOverviewLabels(t: TFunction): SpacesOverviewLabels {
  return {
    title: t("spaces.overview.title"),
    newSpace: t("spaces.overview.newSpace"),
    filterLabel: t("spaces.overview.filterLabel"),
    filterPlaceholder: t("spaces.overview.filterPlaceholder"),
    suggestedHeading: t("spaces.overview.suggestedHeading"),
    confirmedHeading: t("spaces.overview.confirmedHeading"),
    pages: t("spaces.overview.pages"),
    memories: t("spaces.overview.memories"),
    updated: t("spaces.overview.updated"),
    nameLabel: t("spaces.overview.nameLabel"),
    descriptionLabel: t("spaces.overview.descriptionLabel"),
    descriptionPlaceholder: t("spaces.overview.descriptionPlaceholder"),
    create: t("spaces.overview.create"),
    save: t("spaces.overview.save"),
    cancel: t("spaces.overview.cancel"),
    keep: t("spaces.overview.keep"),
    discard: t("spaces.overview.discard"),
    star: t("spaces.overview.star"),
    unstar: t("spaces.overview.unstar"),
    rename: t("spaces.overview.rename"),
    moveUp: t("spaces.overview.moveUp"),
    moveDown: t("spaces.overview.moveDown"),
    delete: t("spaces.overview.delete"),
    confirmDelete: t("spaces.overview.confirmDelete"),
    actionsFor: (name) => t("spaces.overview.actionsFor", { name }),
    dragSpace: (name) => t("spaces.overview.dragSpace", { name }),
    loading: t("spaces.overview.loading"),
    loadError: t("spaces.overview.loadError"),
    mutationError: t("spaces.overview.mutationError"),
    retry: t("spaces.overview.retry"),
    noSuggestions: t("spaces.overview.noSuggestions"),
    noConfirmed: t("spaces.overview.noConfirmed"),
    noResults: t("spaces.overview.noResults"),
    duplicateName: t("spaces.overview.duplicateName"),
    nameRequired: t("spaces.overview.nameRequired"),
  };
}

export function createSpaceDetailCopy(t: TFunction): SpaceDetailCopy {
  return {
    backToSpaces: t("spaceDetail.backToSpaces"),
    cancel: t("spaceDetail.cancel"),
    confirmDeleteSpace: t("spaceDetail.confirmDeleteSpace"),
    deleteSpace: t("spaceDetail.deleteSpace"),
    deleteWarning: t("spaceDetail.deleteWarning"),
    descriptionPlaceholder: t("spaceDetail.descriptionPlaceholder"),
    discard: t("spaceDetail.discard"),
    editDescription: t("spaceDetail.editDescription"),
    keep: t("spaceDetail.keep"),
    keyEntities: t("spaceDetail.keyEntities"),
    loadError: t("spaceDetail.loadError"),
    loading: t("spaceDetail.loading"),
    metrics: {
      entities: t("spaceDetail.metrics.entities"),
      memories: t("spaceDetail.metrics.memories"),
      pages: t("spaceDetail.metrics.pages"),
      updated: t("spaceDetail.metrics.updated"),
    },
    mutationError: t("spaceDetail.mutationError"),
    needsReview: t("spaceDetail.needsReview"),
    noEntities: t("spaceDetail.noEntities"),
    noMemories: t("spaceDetail.noMemories"),
    noPages: t("spaceDetail.noPages"),
    noReview: t("spaceDetail.noReview"),
    notFound: t("spaceDetail.notFound"),
    notUpdated: t("spaceDetail.notUpdated"),
    rawMemories: t("spaceDetail.rawMemories"),
    reasons: {
      needsRefresh: t("spaceDetail.reasons.needsRefresh"),
      sourceConflict: t("spaceDetail.reasons.sourceConflict"),
      sourceUpdated: t("spaceDetail.reasons.sourceUpdated"),
    },
    recentlyRefined: t("spaceDetail.recentlyRefined"),
    relatedLoadError: t("spaceDetail.relatedLoadError"),
    reviewAll: t("spaceDetail.reviewAll"),
    save: t("spaceDetail.save"),
    saveShortcut: t("spaceDetail.saveShortcut"),
    showLess: t("spaceDetail.showLess"),
    showingLatest: (shown, total) => t("spaceDetail.showingLatest", { shown, total }),
    sourceCount: (count) => t("spaceDetail.sourceCount", { count }),
    suggestedLabel: t("spaceDetail.suggestedLabel"),
    viewAllEntities: (count) => t("spaceDetail.viewAllEntities", { count }),
  };
}
