// SPDX-License-Identifier: AGPL-3.0-only
import { useState, useCallback } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import {
  deleteFileChunks,
  clipboardWrite,
  getMemoryDetail,
  type IndexedFileInfo,
} from "../lib/tauri";

function formatTime(ts: number): string {
  return new Date(ts * 1000).toLocaleTimeString([], { hour: "numeric", minute: "2-digit", second: "2-digit" });
}

function formatDate(ts: number): string {
  return new Date(ts * 1000).toLocaleDateString([], { weekday: "short", month: "short", day: "numeric" });
}

function relativeTime(ts: number): string {
  const diff = Math.floor(Date.now() / 1000) - ts;
  if (diff < 60) return "just now";
  if (diff < 3600) return `${Math.floor(diff / 60)}m ago`;
  if (diff < 86400) return `${Math.floor(diff / 3600)}h ago`;
  return `${Math.floor(diff / 86400)}d ago`;
}

interface RecapDetailProps {
  snapshot: IndexedFileInfo;
  onBack: () => void;
}

export default function RecapDetail({ snapshot, onBack }: RecapDetailProps) {
  const queryClient = useQueryClient();
  const [copied, setCopied] = useState(false);

  // Fetch full MemoryItem to get content (IndexedFileInfo lacks it)
  const { data: fullMemory } = useQuery({
    queryKey: ["memory-detail", snapshot.source_id],
    queryFn: () => getMemoryDetail(snapshot.source_id),
  });

  const deleteMutation = useMutation({
    mutationFn: () => deleteFileChunks(snapshot.source, snapshot.source_id),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["indexedFiles"] });
      onBack();
    },
  });

  const summary = fullMemory?.summary ?? snapshot.summary;
  const content = fullMemory?.content;
  const hasSourceContext = content && summary && content !== summary;

  const copyAsContext = useCallback(async () => {
    const space = snapshot.domain ? `**Space:** ${snapshot.domain}` : "";
    const time = `**Time:** ${formatDate(snapshot.last_modified)} ${formatTime(snapshot.last_modified)}`;
    const agent = snapshot.source_agent ? `**Generated by:** ${snapshot.source_agent}` : "";

    const meta = [space, time, agent].filter(Boolean).join("\n");
    const summarySection = `### Summary\n${summary ?? ""}`;
    const sourceSection = hasSourceContext ? `### Source Memories\n${content}` : "";

    const text = [
      "## Activity Recap",
      meta,
      "",
      summarySection,
      ...(sourceSection ? ["", sourceSection] : []),
    ].join("\n");

    await clipboardWrite(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }, [snapshot, summary, content, hasSourceContext]);

  return (
    <div className="w-full h-screen flex flex-col bg-[var(--bg-primary)] overflow-hidden">
      {/* Header */}
      <div className="flex items-start gap-3 pl-[130px] pr-14 py-3 border-b border-[var(--separator)] shrink-0">
        <button
          onClick={onBack}
          className="text-[var(--text-secondary)] hover:text-[var(--text-primary)] transition-colors text-sm shrink-0 mt-0.5"
        >
          &#8249; Back
        </button>
        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-2">
            <h2 className="text-sm font-semibold text-[var(--text-primary)] truncate">
              {snapshot.title}
            </h2>
            <span className="text-[10px] font-medium px-1.5 py-0.5 rounded-full bg-indigo-500/15 text-indigo-400 shrink-0">
              Recap
            </span>
          </div>
          <div className="flex items-center gap-2 mt-1">
            {snapshot.domain && (
              <>
                <span className="text-[11px] text-[var(--text-tertiary)]">
                  {snapshot.domain}
                </span>
                <span className="text-[11px] text-[var(--text-tertiary)]">&middot;</span>
              </>
            )}
            <span className="text-[11px] text-[var(--text-tertiary)]">
              {relativeTime(snapshot.last_modified)}
            </span>
          </div>
        </div>
        <div className="flex items-center gap-1 shrink-0 mt-0.5">
          <button
            onClick={copyAsContext}
            className={`text-[11px] font-medium px-2.5 py-1 rounded-md transition-all flex items-center gap-1 ${
              copied
                ? "bg-emerald-500/15 text-emerald-400"
                : "bg-[var(--accent)]/10 text-[var(--accent)] hover:bg-[var(--accent)]/20"
            }`}
          >
            <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" className="shrink-0">
              <rect x="9" y="9" width="13" height="13" rx="2" ry="2" />
              <path d="M5 15H4a2 2 0 01-2-2V4a2 2 0 012-2h9a2 2 0 012 2v1" />
            </svg>
            {copied ? "Copied!" : "Copy as context"}
          </button>
          <button
            onClick={() => deleteMutation.mutate()}
            disabled={deleteMutation.isPending}
            className="text-[11px] text-[var(--text-tertiary)] hover:text-red-400 transition-colors disabled:opacity-50 px-1.5 py-1"
          >
            {deleteMutation.isPending ? "..." : "Delete"}
          </button>
        </div>
      </div>

      {/* Metadata strip */}
      <div className="px-5 py-2.5 border-b border-[var(--separator)] shrink-0">
        <div className="flex items-center gap-1.5 flex-wrap">
          {snapshot.source_agent && (
            <span className="text-[11px] font-medium px-2 py-0.5 rounded-full bg-indigo-500/15 text-indigo-400">
              {snapshot.source_agent}
            </span>
          )}
          <span className="text-[11px] text-[var(--text-tertiary)] ml-auto">
            {formatDate(snapshot.last_modified)} &middot; {formatTime(snapshot.last_modified)}
          </span>
        </div>
      </div>

      {/* Content */}
      <div className="flex-1 overflow-y-auto px-5 py-4 space-y-4">
        {summary ? (
          <div className="bg-[var(--bg-secondary)] rounded-xl p-4">
            <p className="text-[13px] text-[var(--text-primary)] leading-relaxed whitespace-pre-wrap">
              {summary}
            </p>
          </div>
        ) : (
          <div className="flex flex-col items-center justify-center py-12 gap-2">
            <span className="text-sm text-[var(--text-tertiary)]">No summary available</span>
            <span className="text-[11px] text-[var(--text-tertiary)]/60">This recap has no content</span>
          </div>
        )}

        {/* Source context section */}
        {hasSourceContext && (
          <div>
            <h3
              className="text-[11px] font-medium uppercase tracking-wider mb-2"
              style={{ color: "var(--text-tertiary)", fontFamily: "var(--font-mono, monospace)" }}
            >
              Source Memories
            </h3>
            <div className="rounded-xl p-4" style={{ backgroundColor: "rgba(99, 102, 241, 0.06)" }}>
              <p
                className="text-[12px] leading-relaxed"
                style={{ color: "var(--text-secondary)", whiteSpace: "pre-line" }}
              >
                {content}
              </p>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
